services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base
    depends_on:
      - mssql
    volumes:
      - .:/workspaces/mssql
    stdin_open: true

  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 1433:1433
    environment:
      # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"
      MSSQL_PID: "Developer"
    volumes:
      # - ./data:/var/opt/mssql
      # - ./log:/var/opt/mssql/log
      - ./backup:/var/opt/mssql/backup
